version: "3"
services:
  api:
    build: ./server
    container_name: backend

  client:
    build: ./client
    container_name: frontend

  nginx:
    build: ./nginx
    depends_on:
      - api
      - client
    ports:
      - 80:80

  # jenkins:
  #   build: ./jenkins
  #   privileged: true
  #   user: root
  #   ports:
  #     - 8081:8080
  #     - 50000:50000
  #   container_name: jenkins
  #   volumes:
  #     - ~/jenkins_home:/var/jenkins_home
  #     - /var/run/docker.sock:/var/run/docker.sock
